services:
  frontend:
    build: ./sostool-frontend
    volumes:
      - ./sostool-frontend/src:/frontend/src
    ports:
      - 4200:4200

  backend:
    build: ./sostool-backend
    ports:
      - 8081:8081