services:
  frontend:
    build: ./sostool-frontend
    volumes:
      - ./sostool-frontend/src:/frontend/src
    ports:
      - 127.0.0.1:4200:4200

  backend:
    build: ./sostool-backend
    ports:
      - 127.0.0.1:8081:8081
